# Generated by Django 5.2.1 on 2026-09-09 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFund',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(default=0)),
                ('low_balance_threshold', models.FloatField(default=0)),
                ('approval_threshold', models.FloatField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='accounts.user')),
            ],
            options={
                'db_table': 'databases',
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=16)),
                ('amount', models.FloatField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('next_run', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('database', models.ForeignKey(db_column='database_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='ledger.databasefund')),
            ],
            options={
                'db_table': 'recurring_transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionFund',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=16)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('sender', models.TextField(blank=True, null=True)),
                ('receiver', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('electronic', 'Electronic'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=16)),
                ('mode_data', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('running_balance', models.FloatField()),
                ('receipt_image', models.TextField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('voided_by', models.TextField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('database', models.ForeignKey(db_column='database_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.databasefund')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('entity_type', models.TextField()),
                ('entity_data', models.TextField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='accounts.user')),
            ],
            options={
                'db_table': 'trash',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.user')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['timestamp'], name='idx_audit_timestamp')],
            },
        ),
        migrations.AddIndex(
            model_name='databasefund',
            index=models.Index(fields=['user'], name='idx_databases_user'),
        ),
        migrations.AddIndex(
            model_name='transactionfund',
            index=models.Index(fields=['database'], name='idx_txn_database'),
        ),
    ]
