# Generated by Django 5.2.1 on 2026-09-09 18:53
# Hand-adjusted: the autodetector could not offer a rename prompt for
# databasefund.user -> created_by because the new field's on_delete/null/
# related_name/db_column all differ from the old one, so its default output
# was RemoveField+AddField (data loss). Replaced with the RenameField +
# AlterField pair Django emits when a rename *is* detected with a db_column
# change, so the existing column (and its data) is preserved.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='databasefund',
            name='idx_databases_user',
        ),
        migrations.RenameField(
            model_name='databasefund',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='databasefund',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_databases', to='accounts.user'),
        ),
        migrations.RenameField(
            model_name='transactionfund',
            old_name='receipt_image',
            new_name='receipt_key',
        ),
        migrations.AddField(
            model_name='transactionfund',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to='accounts.user'),
        ),
        migrations.AddIndex(
            model_name='databasefund',
            index=models.Index(fields=['created_by'], name='idx_databases_creator'),
        ),
    ]
