# Generated by Django 5.2.1 on 2026-09-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_owner_viewer_roles'),
        ('ledger', '0002_org_ownership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring', to='accounts.user'),
        ),
    ]
