# Generated by Django 5.2.1 on 2026-09-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recurringtransaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefund',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_column='merged_into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_sources', to='ledger.databasefund'),
        ),
    ]
