# Generated by Django 5.2.1 on 2026-09-10 03:04

import apps.orgs.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('db_connection', apps.orgs.fields.EncryptedTextField()),
                ('storage_config', apps.orgs.fields.EncryptedTextField(blank=True, default='')),
                ('ai_config', apps.orgs.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'orgs',
            },
        ),
        migrations.CreateModel(
            name='JoinCode',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('grants_role', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='orgs.org')),
            ],
            options={
                'db_table': 'join_codes',
            },
        ),
        migrations.CreateModel(
            name='EmailIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_emails', to='orgs.org')),
            ],
            options={
                'db_table': 'email_index',
                'constraints': [models.UniqueConstraint(fields=('email', 'org'), name='uniq_email_per_org')],
            },
        ),
    ]
